#!/bin/sh
#
# git pre-commit script to auto update the 'updated at' timestamp on every commit
#
echo -n "const timestamp = '" >  client/src/commit_timestamp.js
echo -n `date +"[%D %H %M %S]"` >> client/src/commit_timestamp.js
echo "'; export default timestamp;" >>  client/src/commit_timestamp.js
git add client/src/commit_timestamp.js
echo "Updated the time in commit_timestamp.js"
exit 0